### ISSUE TITLE
Clarify documentation on input data

### ISSUE THREAD

**Issue by marisn** [greigpaterson/AnalySize#2]
Although most of information on input data formatting can be deduced from example data, a clear text on AnalySize expectations would be beneficial. Documentation should provide answers to following questions:
- What are measurement units of grain size bins?
  - Are arbitrary units supported to analyse non-granulometry data?
- Should bins be equally spaced?
- Should bins be sorted or bin order is arbitrary?
- Should empty observations be filled with 0?
- Units of observed sample values.
- What should be done with pan values (included/excluded/assigned to a virtual bin)?

**Comment by greigpaterson** [comment]
Hi Maris, thanks for raising these comments, I'll work on integrating them into the documentation. To respond to you directly:

- The grain size units are assumed to be microns. This is implicit in the pre-formatted machine outputs, but not for the user defined text/Excel files.

- One of the reasons for having custom text input was for handling non-granulometry data, so arbitrary bin units are possible. This has already been done for unmixing detrital zircon age distributions (http://dx.doi.org/10.1016/j.epsl.2017.07.044). If you do want to look at non-granulometry data, get in touch, as there may be better way of handling the input/processing/output.

- Bins don't have to be equally spaced

- Bin order doesn't matter, all data are sorted to have ascending bins

- The unit of the specimen values can be somewhat arbitrary. For grain size counting they are simply grain counts per bin, or normalized to a frequency (sum to one or 100%). All value read in are normalized to a frequency.

- Generally, empty bins should be assigned zero, but if you are measuring with highly discrete method (i.e., sieving), it is best to stick with the sizes you have and not to artificially pad the data with zeros. But see comment below.

- Generally, AnalySize unmixing algorithms work better for laser diffraction grain size data where the number of bins is >>10, this is what AnalySize is primarily designed for. That said, it doesn't preclude other data types, but these may come with issues of numerical stability and interpretability (fewer grain size bins puts a limit of the power to differentiate different end members) and this would need to be assessed on dataset by dataset basis. So some sieved datasets may be OK, but if the number of bins is small, unmixing may not work well.
For dealing with the pan data, you can assign it to a virtual bin and unmixing the dataset using non-parametric unmixing (parametric won't work). In essence, non-parametric unmixing ignores the value of the grain size bin and just finds patterns among the bins (the actual grain size bin value is like a label that we use to visualize the data). You will have to keep in mind the virtual bin is not a real discrete grain size when interpreting, but it will contain useful information about the < Xµm fraction.

Hope all this helps and let me know if you have any other questions/comments/suggestions.

**Comment by marisn** [comment]
Thank you for your reply. I see that I guessed almost everything correctly. Unfortunately I work with sieving data (medium to well sorted sand) and thus number of (non-empty) bins and samples is a bit of an issue.  

Your comments are really good and thus should be added to the documentation. Explicit is better than implicit.
